[package]
name = "k8s-basic-auth-translator"
version = "0.0.0-development"
edition = "2021"

[dependencies]
clap = { version = "3.0.14", features = ["derive", "env"] }
env_logger = "0.9.0"
k8s-openapi = { version = "0.14.0", features = ["v1_22"] }
kube = { version = "0.69.0" }
log = "0.4.14"
parking_lot = "0.12.0"
prost = "0.9"
prost-types = "0.9"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
tonic = { version = "0.6", features = ["tls", "tls-roots", "tls-roots-common"] }
tonic-types = "0.4"

[build-dependencies]
tonic-build = "0.6"
