version: '3.8'
services:
  app:
    build:
      context: example/app
      dockerfile: Dockerfile
    links:
      - envoy-api
    command:
      - "-api=http://envoy-api:8500/albums"

  envoy-app:
    image: envoyproxy/envoy-alpine:v1.17-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.app.yaml:/etc/envoy/envoy.yaml:ro
    links:
      - app
    ports:
      - 8600:8600

  api:
    build:
      context: example/api
      dockerfile: Dockerfile

  envoy-api:
    image: envoyproxy/envoy-alpine:v1.17-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.api.yaml:/etc/envoy/envoy.yaml:ro
    links:
      - api
    ports:
      - 8500:8500
