version: '3.8'
services:
  pki:
    image: ghcr.io/wirepact/k8s-pki:1.1.0
    command:
      - '-local'
    ports:
      - 8080:8080

  app:
    build:
      context: example/app
      dockerfile: Dockerfile
    networks:
      - app-net
    environment:
      HTTP_PROXY: http://envoy-app:8700
    command:
      - '-api=http://envoy-api:8500/albums'

  envoy-app:
    image: envoyproxy/envoy-alpine:v1.20-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.app.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - app-net
    ports:
      - 8600:8600

  api:
    build:
      context: example/api
      dockerfile: Dockerfile
    networks:
      - app-net

  envoy-api:
    image: envoyproxy/envoy-alpine:v1.20-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.api.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - app-net
    ports:
      - 8500:8500

networks:
  app-net:
    driver: bridge
