version: '3.8'
services:
  pki:
    image: ghcr.io/wirepact/k8s-pki:latest
    environment:
      - DEBUG=true
      - LOCAL=true
    ports:
      - 8080:8080

  app:
    image: ghcr.io/wirepact/demo-applications/basic-auth-backend-app:latest
    environment:
      - HTTP_PROXY=http://envoy-app:8500
      - PORT=8001
      - AUTH_USER=admin
      - AUTH_PASS=supersecret
      - API_URL=http://envoy-api:9000/swapi/people
    networks:
      - app-net

  envoy-app:
    image: envoyproxy/envoy:v1.20-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.app.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - app-net
    ports:
      - 8000:8000

  api:
    image: ghcr.io/wirepact/demo-applications/basic-auth-api:latest
    environment:
      - PORT=9001
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=supersecret
    networks:
      - app-net

  envoy-api:
    image: envoyproxy/envoy:v1.20-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.api.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - app-net
    ports:
      - 9000:9000

networks:
  app-net:
    driver: bridge
